import Head from "next/head";
import Product from "../components/Products";
import React from "react";
import Slideshow from "../components/Slideshow";

export default function Home() {
  const [item, setItem] = React.useState([]);
  React.useEffect(() => {
    const url = "http://localhost:9000/products";
    fetch(url, {
      method: "GET",
    })
      .then((response) => response.json())
      .then((json) => {
        setItem(json);
      })
      .catch((error) => {
        // Nếu có lỗi
        console.error(error);
      });
  }, []);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <img src="https://insieutoc.vn/wp-content/uploads/2021/02/mau-banner-quang-cao-khuyen-mai.jpg" alt="banner" /> */}
      <div>
        <Slideshow />
      </div>

      <div className="mt-9 mx-14	">
        <div className="row">
          <div className="w-full text-center">
            <h1 className="text-5xl	pb-2.5	">Our Products</h1>
            <hr className="pb-2.5" />
          </div>
          <div className="grid grid-cols-4 gap-4">
            {item.map((p: any) => {
              return (
                <div key={p._id} className="">
                  <Product
                    imgUlr={`http://localhost:9000${p.imageUrl}`}
                    name={p.name}
                    price={p.price}
                    product={p}
                    id={p.id}
                  />
                </div>
              );
            })}
          </div>
        </div>
      </div>
    </>
  );
}
